# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 0 * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: assets/metrics.svg
          config_animations: yes
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: mr-u0b0dy
          template: classic
          base: ""
          config_timezone: Asia/Calcutta
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
          plugin_languages: yes
          #plugin_languages_analysis_timeout: 15
          #plugin_languages_analysis_timeout_repositories: 7.5
          #plugin_languages_categories: markup, programming
          plugin_languages_ignored: html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell, gnuplot
          plugin_languages_colors: github
          #plugin_languages_indepth: yes
          plugin_languages_limit: 8
          plugin_languages_details: percentage
          #plugin_languages_recent_categories: markup, programming
          #plugin_languages_recent_days: 14
          #plugin_languages_recent_load: 300
          #plugin_languages_sections: most-used
          #plugin_languages_threshold: 0%
